services:
  postgres_news:
    image: postgres:16.2-alpine
    container_name: postgres_news_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54123:5432"
    volumes:
      - postgres_news_data:/var/lib/postgresql/data
    shm_size: 256m
    networks:
      - news_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  redis_news:
    image: redis:6.2-alpine
    container_name: redis_news
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --maxmemory 400mb --maxmemory-policy allkeys-lru
    networks:
      - news_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  news:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: news_image:latest
    container_name: news
    restart: unless-stopped
    depends_on:
      - postgres_news
      - redis_news
    ports:
      - "8188:8188"
    env_file:
      - .env
    environment:
      JAVA_OPTS: "-Xms512m -Xmx4g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC"
    networks:
      - news_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6G
        reservations:
          cpus: '0.5'
          memory: 1536M

volumes:
  postgres_news_data:

networks:
  news_network:
    name: news_network
    driver: bridge