#spring:
#  data:
#    mongodb:
#      port: 27017
#      host: 10.8.0.3
#      database: users

#spring:
#  data:
#    mongodb:
#      uri: mongodb://10.8.0.3:27017/users

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/users
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/test09?allowPublicKeyRetrieval=true
