version: "3.9"
services:
  service-qa:
    build:
      context: ../../
      dockerfile: ./docker/qa/Dockerfile
    container_name: shop-sport-service-qa
    ports:
      - ${PORT_EXTERNAL_PROD}:${PORT_INTERNAL}
    environment:
      DATASOURCE_URL: ${MYSQL_URL_PROD}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PORT: ${PORT_INTERNAL}
      OPENAPI_PORT_EXTERNAL: ${PORT_EXTERNAL_PROD}
      PROFILE: ${PROFILE_PROD}
    networks:
      - shop-sport-network
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  db-data:
networks:
  shop-sport-network:
    external:
      name: shop-sport-network
