spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
#    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=news_db}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/news_db}

    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://soar-fe.lab.ncc.local}