spring:
  application:
    name: openlearnhub
  profiles:
    active:
      - dev
      - dev-local
  liquibase:
    change-log: classpath:db/master.xml
server:
  port: 8088

logging:
  level:
    sql: debug
conditional:
  bean:
    messageService: true