spring:
  application:
    name: profiling
  profiles:
    active:
      - dev
      - dev-local
  liquibase:
    change-log: classpath:db/master.xml
server:
  port: 8081

logging:
  level:
    sql: debug
conditional:
  bean:
    messageService:
      enabled: true
