spring:
  application:
    name: profiling
  profiles:
    active:
      - dev
      - dev-local
  liquibase:
    change-log: classpath:db/master.xml

conditional:
  bean:
    enabled: false
server:
  port: 8081

logging:
  level:
    sql: debug