spring:
  data:
    mongodb:
      port: 27017
      host: 10.8.0.3
      database: users
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/test09?allowPublicKeyRetrieval=true
